apiVersion: apps/v1
kind: Deployment
metadata:
  name: Muxi-staging
  labels:
    app: muxi-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: muxi-staging
  template:
    metadata:
      labels:
        app: muxi-staging
    spec:
      containers:
        - name: muxi-frontend-staging
          image: akashbhardwaj24/muxi-frontend:bed56775066a3013c4e603878fb7a29e5e2d6d65
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
        - name: muxi-backend-staging
          image: akashbhardwaj24/muxi-backend:bed56775066a3013c4e603878fb7a29e5e2d6d65
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

